### PR TITLE
chore: Fix pre-commit.

### PR DESCRIPTION
**Pull request by blakeli0**
fixes: #1270 

Update pre-commit to use `mvn install` instead of `mvn test` as `gapic-generator-java` is dependent on gax test jars. This is also mimicking the same behavior in [ci](https://github.com/googleapis/gapic-generator-java/blob/d1a16195937df041f65a52717ddf9dc6ceb09b4f/.github/workflows/ci-maven.yaml#L25).

### CODE REVIEW

**Comment by lqiu96** [comment]
Ran this locally with some Java changes:
```
(14:11:28) ERROR: /private/var/tmp/_bazel_lawrenceqiu/848933e5d291df54c266044a93c65004/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_arm64'
```

Also would it be possible to just run `mvn fmt:format` in the git pre-commit hooks instead of having it fail and then running it seperately?

**Comment by blakeli0** [comment]
> Also would it be possible to just run `mvn fmt:format` in the git pre-commit hooks instead of having it fail and then running it seperately?

I would keep them separately as the `pre-commit` is supposed to be checks only, doing formatting also in `pre-commit` would mixing concerns. Also you would need to run `git add .` again to add the formatted files, which is something I don't think we should do as well in `pre-commit`   

```
(14:11:28) ERROR: /private/var/tmp/_bazel_lawrenceqiu/848933e5d291df54c266044a93c65004/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_arm64'
```
This might be an M1 only issue. Which step did it fail? Integration tests?

**Comment by lqiu96** [comment]
> > Also would it be possible to just run `mvn fmt:format` in the git pre-commit hooks instead of having it fail and then running it seperately?
> 
> I would keep them separately as the `pre-commit` is supposed to be checks only, doing formatting also in `pre-commit` would mixing concerns. Also you would need to run `git add .` again to add the formatted files, which is something I don't think we should do as well in `pre-commit`

I see -- that's a valid point. The only reason I bring this up is because when I had formatting issue in the past, I've just ended up running `mvn fmt:format` immediately after. Unless there is a reason to spot check the formatting issues, I think it *could* be a nice QOL for the pre-commit hooks to just format it.

> ```
> (14:11:28) ERROR: /private/var/tmp/_bazel_lawrenceqiu/848933e5d291df54c266044a93c65004/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_arm64'
> ```
> 
> This might be an M1 only issue. Which step did it fail? Integration tests?


More from the logs:
```
Repository rule jvm_import_external defined at:
  /private/var/tmp/_bazel_lawrenceqiu/848933e5d291df54c266044a93c65004/external/bazel_tools/tools/build_defs/repo/jvm.bzl:217:38: in <toplevel>
(14:11:28) ERROR: Analysis of target '//test/integration:com.google.cloud.iam.credentials.v1.IAMCredentialsClientTest' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
```
Looks to be the golden ITs

**Comment by lqiu96** [comment]
This was resolved when I used v5.x+ of bazel. Possible solution found via: https://github.com/bazelbuild/bazel/issues/13514

**Review by lqiu96 — APPROVED** [review]

**Pull request merged**
