### PR TITLE
feat: Update to non-eager FutureListener

### PR DESCRIPTION
**Pull request by lqiu96**
Work has been done in https://github.com/googleapis/gax-java/pull/1878.

This is the result of the patch file and migrating the PRs to the GAPIC monorepo.

### CODE REVIEW

**Comment by lqiu96** [comment]
`ci / build (8)` job failure:
```
Run echo "Building Storage lib from generated source..."
Building Storage lib from generated source...
(21:15:16) INFO: Current date is 2022-12-19
(21:[15](https://github.com/googleapis/gapic-generator-java/actions/runs/3735156598/jobs/6338068902#step:10:16):[16](https://github.com/googleapis/gapic-generator-java/actions/runs/3735156598/jobs/6338068902#step:10:17)) Loading: 
(21:15:16) Loading: 0 packages loaded
(21:15:[17](https://github.com/googleapis/gapic-generator-java/actions/runs/3735156598/jobs/6338068902#step:10:18)) Analyzing: target @com_google_googleapis//google/storage/v2:google-cloud-storage-v2-java (1 packages loaded, 0 targets configured)
(21:15:17) ERROR: /home/runner/work/gapic-generator-java/gapic-generator-java/rules_java_gapic/BUILD.bazel:7:8: //rules_java_gapic:gradlew: no such attribute 'extension' in '_real_pkg_tar' rule
(21:15:17) ERROR: /home/runner/work/gapic-generator-java/gapic-generator-java/rules_java_gapic/BUILD.bazel:7:8: //rules_java_gapic:gradlew: no such attribute 'files' in '_real_pkg_tar' rule
(21:15:17) ERROR: /home/runner/work/gapic-generator-java/gapic-generator-java/rules_java_gapic/BUILD.bazel:7:8: //rules_java_gapic:gradlew: no such attribute 'mode' in '_real_pkg_tar' rule
([21](https://github.com/googleapis/gapic-generator-java/actions/runs/3735156598/jobs/6338068902#step:10:22):15:17) ERROR: /home/runner/work/gapic-generator-java/gapic-generator-java/rules_java_gapic/BUILD.bazel:7:8: //rules_java_gapic:gradlew: no such attribute 'modes' in '_real_pkg_tar' rule
(21:15:17) ERROR: /home/runner/.cache/bazel/_bazel_runner/1f815583ebc8da6875b9074f31ba9a5d/external/com_google_googleapis/google/storage/v2/BUILD.bazel:93:31: Target '//rules_java_gapic:gradlew' contains an error and its package is in error and referenced by '@com_google_googleapis//google/storage/v2:google-cloud-storage-v2-java'
(21:15:17) ERROR: Analysis of target '@com_google_googleapis//google/storage/v2:google-cloud-storage-v2-java' failed; build aborted: Analysis failed
(21:15:17) INFO: Elapsed time: 1.981s
(21:15:17) INFO: 0 processes.
(21:15:17) FAILED: Build did NOT complete successfully (5 packages loaded, 5 targets configured)
Error: Process completed with exit code 1.
```

Investigating...

**Comment by suztomo** [comment]
All checks are green except SonarCloud.

**Comment by lqiu96** [comment]
> All checks are green except SonarCloud.

Thanks for resolving the issue @suztomo! I've re-ran the Sonar check and it passed -- Seems like it was a transient issue.

CC: @blakeli0 Can you take a look at this when you get a chance?

**Review by blakeli0 — APPROVED** [review]
LGTM

**Pull request merged**
