### PR TITLE
build: not relying on gax's zip archive

### PR DESCRIPTION
**Pull request by suztomo**
gax-java is now part of gapic-generator-java. No need to fetch
the released zip file to get the dependencies list.

In future, we'll revisit how we maintain the dependencies to
the user of gapic-generator-java, even for self-service users.

### CODE REVIEW

**Comment by suztomo** [comment]
Unclear error.

```
2023-01-25T19:07:41.5888110Z [INFO] ------------------------------------------------------------------------
2023-01-25T19:07:41.5888197Z [INFO] Reactor Summary:
2023-01-25T19:07:41.5888262Z [INFO] 
2023-01-25T19:07:41.5888507Z [INFO] GAPIC Showcase Client Core Parent 0.0.1-SNAPSHOT ... SUCCESS [  2.602 s]
2023-01-25T19:07:41.5888756Z [INFO] proto-gapic-showcase-v1beta1 0.0.1-SNAPSHOT ........ FAILURE [05:48 min]
2023-01-25T19:07:41.5888979Z [INFO] grpc-gapic-showcase-v1beta1 0.0.1-SNAPSHOT ......... SKIPPED
2023-01-25T19:07:41.5889176Z [INFO] GAPIC Showcase Client 0.0.1-SHAPSHOT ............... SKIPPED
2023-01-25T19:07:41.5889401Z [INFO] ------------------------------------------------------------------------
2023-01-25T19:07:41.5889482Z [INFO] BUILD FAILURE
2023-01-25T19:07:41.5889711Z [INFO] ------------------------------------------------------------------------
2023-01-25T19:07:41.5889800Z [INFO] Total time:  05:52 min
2023-01-25T19:07:41.5889962Z [INFO] Finished at: 2023-01-25T19:07:41Z
2023-01-25T19:07:41.5890184Z [INFO] ------------------------------------------------------------------------
2023-01-25T19:07:41.5890725Z [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.0:exec (verify-showcase) on project proto-gapic-showcase-v1beta1: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

**Comment by suztomo** [comment]
SonarCloud failed:

```
Error:  Failures: 
Error:    BatcherImplTest.testThrottlingBlocking:897 
Wanted but not invoked:
apiCallContext.withOption(
    <Capturing argument>,
    <Capturing argument>
);
-> at com.google.api.gax.batching.BatcherImplTest.testThrottlingBlocking(BatcherImplTest.java:897)
Actually, there were zero interactions with this mock.

[INFO] 
Error:  Tests run: 529, Failures: 1, Errors: 0, Skipped: 0
```

Retrying.

**Comment by suztomo** [comment]
`~/gapic-generator-java $ bazel run //showcase:verify_grpc` succeeded in my laptop. Strange.

@mpeddada1 @burkedavison  The failure is unclear. In another pull request, would you separate golden test and integration tests?

Screenshot 2023-01-25 at 2 59 13 PM

**Review by meltsufin — APPROVED** [review]

**Comment by suztomo** [comment]
It turned out that the failure is about golden file. Not integration tests.

**Pull request merged**
