### PR TITLE
chore: merging generator-related repos

### PR DESCRIPTION
**Pull request by suztomo**
Merging gapic-generator-java, gax-java, api-common-java, java-common-protos, and java-iam

Command: https://bit.googleplex.com/#/suztomo/6448796428926976

### CODE REVIEW

**Review by meltsufin — COMMENTED** [review]
@suztomo Can you provide a list of commands used to generate this PR?
It's impossible to review the PR, but a script or a list of commands would be more feasable.

**Comment by suztomo** [comment]
Here is the command: https://bit.googleplex.com/#/suztomo/6448796428926976

**Review by meltsufin — APPROVED** [review]
LGTM. Please be careful not to just squash and merge.

**Comment by suztomo** [comment]
cla/google complains "PR exceeds 250 commit limit.

**Comment by suztomo** [comment]
I'm creating a real one.

**Comment by suztomo** [comment]
Cont. : https://github.com/googleapis/gapic-generator-java/pull/1142

**Pull request closed without merging**
